### ISSUE TITLE
Inflow variables not available in advanced flow

### ISSUE THREAD

**Issue by paxus42** [windrage-development/homey-hesa-fredrik#1]
When I moved from my old Homey to the newest one I wanted all flows to be advanced. However, for Hesa Fredrik that was not possible due to that the inflow variables Testmeddelande was not available as a booloean.

**Comment by TheodorStorm** [comment]
I am using Hesa Fredrik in an advanced flow, using the "Testmeddelande" variable as a boolean. Feel free to debug and create a pull request if you find an issue that is related to the Homey 2023 version.

![Skärmavbild 2023-09-10 kl  09 33 33](https://github.com/TheodorStorm/homey-hesa-fredrik/assets/12745431/dddfbb6a-ee13-4978-83e1-335dcd308a91)
